<$ROOT/mkconfig

TARG=\
	dom.dis\
	html.dis\
	css.dis\
	style.dis\

MODULES=

SYSMODULES=\
	sys.m\
	web/dom.m\
	web/html.m\
	web/css.m\
	web/style.m\
	math.m\
	bufio.m\
	convcs.m\

DISBIN=$ROOT/dis/lib/web

<$ROOT/mkfiles/mkdis
