// Phase 1c hellaphone (INFR-107 / INFR-110).
//
// Gradle settings for the InferNode Android app. The app shell lives in
// android-app/app/ and consumes a prebuilt libemu.so produced by the
// existing build-android-ndk-arm64.sh + (eventually) build-android-apk.sh
// drivers — i.e. Gradle is not the source of truth for the C build, it
// just packages the artefacts.

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "infernode"

// INF-17: a standard Android Studio install lives at ~/Library/Android/sdk
// and does not export ANDROID_HOME. Write local.properties when the SDK
// can be found and no usable sdk.dir is already set, so `./gradlew` works
// without a prior session's environment.
fun discoverAndroidSdk(): java.io.File? {
    val candidates = listOfNotNull(
        System.getenv("ANDROID_HOME"),
        System.getenv("ANDROID_SDK_ROOT"),
        "${System.getProperty("user.home")}/Library/Android/sdk",
        "${System.getProperty("user.home")}/Android/Sdk",
    ).map { path -> java.io.File(path) }
    return candidates.firstOrNull { f -> f.isDirectory }
}


fun localPropertiesSdk(file: java.io.File): java.io.File? {
    if (!file.isFile) return null
    val raw = file.readLines()
        .map { it.trim() }
        .firstOrNull { it.startsWith("sdk.dir=") }
        ?.removePrefix("sdk.dir=")
        ?.replace("\\:", ":")
        ?.replace("\\\\", "\\")
        ?: return null
    val dir = java.io.File(raw)
    return if (dir.isDirectory) dir else null
}

val localPropsFile = file("local.properties")
if (localPropertiesSdk(localPropsFile) == null) {
    val sdk = discoverAndroidSdk()
    if (sdk != null) {
        val escaped = sdk.absolutePath.replace("\\", "\\\\").replace(":", "\\:")
        val header = "# Generated by InferNode SDK discovery (INF-17). Per-machine; not tracked."
        val kept = if (localPropsFile.exists()) {
            localPropsFile.readLines().filterNot { it.trim().startsWith("sdk.dir=") }
        } else {
            emptyList()
        }
        localPropsFile.writeText(
            (listOf(header) + kept + "sdk.dir=$escaped").joinToString("\n") + "\n",
        )
    }
}

include(":app")
